### ISSUE TITLE
cannot import name timezone

### ISSUE THREAD

**Issue by soyoungboy** [Tim9Liu9/python_spider_jobs#1]
timezone这个无法导入，python 3.6.1环境
Traceback (most recent call last):
  File "D:/python_study/python_spider_jobs-master/main.py", line 9, in <module>
    from datetime import datetime,timezone,timedelta
ImportError: cannot import name timezone

**Comment by Tim9Liu9** [comment]
本人在windows7的python3.5、python3.6.1，都没有问题。在ubuntu14.4的python3.4上测试过也没有问题。
